### ISSUE TITLE
desktop_3dtiles_viewer.exe is detected as a IDP.Generic virus by Avast

### ISSUE THREAD

**Issue by idimitrovski** [ebeaufay/desktop-3dtiles-viewer#1]
Just downloaded the first release and Avast antivirus detects the exe as a potential threat.

**Comment by ebeaufay** [comment]
So, Avast still exists 😂

Anyhow thanks for letting me know. I can promise you there's no antivirus, It's just a windows flutter app with a web view.

It probably complains because it's a loose exe file without an installer but feel free to build the flutter app yourself

**Comment by ebeaufay** [comment]
Ah apparently it's a known issue and fixed with the latest dart SDK, thanks
